### ISSUE TITLE
The attribute 'title' is required but missing.

### ISSUE THREAD

**Issue by indrisepos** [collabpl/magento2-module-consent-mode#3]
Hi, Thank you very much for the module, I started testing it.
I got an error in developer mod in admin. 'title' was missing from acl.xml. My system: Magetno 2.4.6-p2, php8.1. See details:

`1 exception(s):
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 19

Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 19

<pre>#1 Magento\Framework\Acl\Builder\Proxy->getAcl() called at [vendor/magento/module-backend/Model/Auth/Session.php:132]
#2 Magento\Backend\Model\Auth\Session->refreshAcl() called at [generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php:23]
#3 Magento\Backend\Model\Auth\Session\Interceptor->refreshAcl() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:144]
#4 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#5 Mageplaza\Reports\Controller\Adminhtml\Dashboard\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#6 Mageplaza\Reports\Controller\Adminhtml\Dashboard\Index\Interceptor->___callPlugins() called at [generated/code/Mageplaza/Reports/Controller/Adminhtml/Dashboard/Index/Interceptor.php:32]
#7 Mageplaza\Reports\Controller\Adminhtml\Dashboard\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#8 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#9 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#10 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#14 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#15 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#16 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#17 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>`

**Comment by jemoon** [comment]
@indrisepos issue has been fixed in latest 1.0.2 release. Thanks for the issue :)
