### ISSUE TITLE
Reject All Redirect Behaviour

### ISSUE THREAD

**Issue by kestraly** [collabpl/magento2-module-consent-mode#5]
Just a small issue really. The reject all should be the same as other sites, accepting only essential cookies on rejection

```
 case 'reject':
                    window.location.href = this.moduleConfig.noCookiesUrl;
                    break;
```

To something like

```
case 'reject':
this.handleNativeConsent();
consent['minimal'] = true;
break;
```

**Comment by jemoon** [comment]
@kestraly thanks for bringing it up to attention, I'm not sure if we should set minimals on rejection in order to fully comply with GDPR or any other privacy laws. Will try to analyse/check that soon and maybe I will add additional config in backend in future release

**Comment by kestraly** [comment]
I'm not sure I've found a site that doesn't allow required cookies only on rejection. 

It was brought to my attention after customers expected behaviour be that the notification disappear and they continue to browse with required cookies only. 

The GDPR and privacy laws allow for required cookies only because the notification is to allow for users to decide how much they are to be tracked by 3rd parties.

I'll let you decide however from experience it's an inconvenience to decline cookies but not be able to continue to browse the site.

**Comment by taskula** [comment]
> I will add additional config in backend in future release

I would love to see this!

**Comment by jemoon** [comment]
@kestraly, @taskula 
Additional config was added, details can be checked at Readme.
